[0m11:41:54.711157 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B3BECD360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B3D5916C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B3D5914B0>]}


============================== 11:41:54.723499 | 314b79aa-0238-4202-a40a-78d72977ee4f ==============================
[0m11:41:54.723499 [info ] [MainThread]: Running with dbt=1.9.1
[0m11:41:54.724498 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Felipe\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:41:54.970325 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': WindowsPath('C:/Users/Felipe/.dbt')}
[0m11:41:54.971325 [info ] [MainThread]: Creating dbt configuration folder at 
[0m11:42:14.015168 [debug] [MainThread]: Starter project path: c:\Users\Felipe\Documents\GitHub\Azure-Data-Eng-Pipeline\.venv\lib\site-packages\dbt\include\starter_project
[0m11:42:14.105678 [info ] [MainThread]: 
Your new dbt project "medallion_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:42:14.107486 [info ] [MainThread]: Setting up your profile.
[0m11:42:24.046662 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m11:42:24.047677 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m11:42:24.047677 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m11:45:35.030252 [info ] [MainThread]: Profile medallion_dbt written to C:\Users\Felipe\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m11:45:35.033263 [debug] [MainThread]: Command `dbt init` succeeded at 11:45:35.032252 after 220.41 seconds
[0m11:45:35.034250 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B3BECD360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B3D591810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B3D5F7460>]}
[0m11:45:35.034250 [debug] [MainThread]: Flushing usage events
[0m11:45:35.476220 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:48:30.088584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE9C8CD300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE9DF916C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE9DF91450>]}


============================== 11:48:30.102303 | 6103dcc4-b76a-4d6d-bc5f-39f2f28e8cd3 ==============================
[0m11:48:30.102303 [info ] [MainThread]: Running with dbt=1.9.1
[0m11:48:30.105314 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Felipe\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:48:30.162178 [info ] [MainThread]: dbt version: 1.9.1
[0m11:48:30.164174 [info ] [MainThread]: python version: 3.10.11
[0m11:48:30.164174 [info ] [MainThread]: python path: c:\Users\Felipe\Documents\GitHub\Azure-Data-Eng-Pipeline\.venv\Scripts\python.exe
[0m11:48:30.165683 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m11:48:31.262798 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m11:48:31.263810 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m11:48:31.266862 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m11:48:32.266029 [info ] [MainThread]: Using profiles dir at C:\Users\Felipe\.dbt
[0m11:48:32.267857 [info ] [MainThread]: Using profiles.yml file at C:\Users\Felipe\.dbt\profiles.yml
[0m11:48:32.269399 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Felipe\Documents\GitHub\Azure-Data-Eng-Pipeline\dbt_project.yml
[0m11:48:32.270387 [info ] [MainThread]: adapter type: databricks
[0m11:48:32.270387 [info ] [MainThread]: adapter version: 1.9.2
[0m11:48:32.271390 [info ] [MainThread]: Configuration:
[0m11:48:32.273393 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m11:48:32.274392 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m11:48:32.275394 [info ] [MainThread]: Required dependencies:
[0m11:48:32.276405 [debug] [MainThread]: Executing "git --help"
[0m11:48:32.350396 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:48:32.351405 [debug] [MainThread]: STDERR: "b''"
[0m11:48:32.352393 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:48:32.353394 [info ] [MainThread]: Connection:
[0m11:48:32.353394 [info ] [MainThread]:   host: adb-196426690711727.7.azuredatabricks.net
[0m11:48:32.354401 [info ] [MainThread]:   http_path: sql/protocolv1/o/196426690711727/0122-105803-der2qlw
[0m11:48:32.355393 [info ] [MainThread]:   catalog: hive_metastore
[0m11:48:32.355393 [info ] [MainThread]:   schema: saleslt
[0m11:48:32.357400 [info ] [MainThread]: Registered adapter: databricks=1.9.2
[0m11:48:32.812094 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2193519148000, session-id=None, name=debug, idle-time=0s, acquire-count=0, language=None, thread-identifier=(14220, 9916), compute-name=) - Creating connection
[0m11:48:32.813042 [debug] [MainThread]: Acquiring new databricks connection 'debug'
[0m11:48:32.814571 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2193519148000, session-id=None, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(14220, 9916), compute-name=) - Acquired connection on thread (14220, 9916), using default compute resource
[0m11:48:32.814571 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2193519148000, session-id=None, name=debug, idle-time=0.0005261898040771484s, acquire-count=1, language=None, thread-identifier=(14220, 9916), compute-name=) - Checking idleness
[0m11:48:32.816115 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2193519148000, session-id=None, name=debug, idle-time=0.0015492439270019531s, acquire-count=1, language=None, thread-identifier=(14220, 9916), compute-name=) - Retrieving connection
[0m11:48:32.816115 [debug] [MainThread]: Using databricks connection "debug"
[0m11:48:32.817120 [debug] [MainThread]: On debug: select 1 as id
[0m11:48:32.817863 [debug] [MainThread]: Opening a new connection, currently in state init
[0m11:48:33.670150 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2193519148000, session-id=43ce6e71-cfbb-4306-9c4d-15e877e551b7, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(14220, 9916), compute-name=) - Connection created
[0m11:48:33.672139 [debug] [MainThread]: Databricks adapter: Cursor(session-id=43ce6e71-cfbb-4306-9c4d-15e877e551b7, command-id=Unknown) - Created cursor
[0m11:48:36.927964 [debug] [MainThread]: SQL status: OK in 4.110 seconds
[0m11:48:36.930959 [debug] [MainThread]: Databricks adapter: Cursor(session-id=43ce6e71-cfbb-4306-9c4d-15e877e551b7, command-id=6972edee-f8e1-4df9-a2ad-fe036834b1ac) - Closing cursor
[0m11:48:36.932953 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2193519148000, session-id=43ce6e71-cfbb-4306-9c4d-15e877e551b7, name=debug, idle-time=0.0s, acquire-count=0, language=None, thread-identifier=(14220, 9916), compute-name=) - Released connection
[0m11:48:36.933985 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m11:48:36.936064 [info ] [MainThread]: [31m1 check failed:[0m
[0m11:48:36.937013 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Felipe\Documents\GitHub\Azure-Data-Eng-Pipeline\dbt_project.yml> not found

[0m11:48:36.939046 [debug] [MainThread]: Command `dbt debug` failed at 11:48:36.937936 after 6.98 seconds
[0m11:48:36.939046 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m11:48:36.940036 [debug] [MainThread]: On debug: Close
[0m11:48:36.940036 [debug] [MainThread]: Databricks adapter: Connection(session-id=43ce6e71-cfbb-4306-9c4d-15e877e551b7) - Closing connection
[0m11:48:37.326479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE9C8CD300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FE9DF9AC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEB7EDF5E0>]}
[0m11:48:37.327485 [debug] [MainThread]: Flushing usage events
[0m11:48:37.756200 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:57:33.522551 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002ECA26CD2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002ECA3DEBA00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002ECA3DEBBE0>]}


============================== 12:57:33.527061 | 483aa66a-b114-49c8-ba27-ae5265454877 ==============================
[0m12:57:33.527061 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:57:33.528065 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Felipe\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt snapshot', 'send_anonymous_usage_stats': 'True'}
[0m12:57:33.529064 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Felipe\Documents\GitHub\Azure-Data-Eng-Pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:57:33.530460 [debug] [MainThread]: Command `dbt snapshot` failed at 12:57:33.530460 after 0.09 seconds
[0m12:57:33.530460 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002ECA26CD2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002ECA3DEB910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002ECA3DEB940>]}
[0m12:57:33.531452 [debug] [MainThread]: Flushing usage events
[0m12:57:33.967223 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:42:56.619732 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A96BCD2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A984958D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A984956F0>]}


============================== 13:42:56.661489 | 166330b4-3eec-4841-870a-c8f3d30c4e6c ==============================
[0m13:42:56.661489 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:42:56.662496 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Felipe\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:42:56.663488 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Felipe\Documents\GitHub\Azure-Data-Eng-Pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:42:56.665499 [debug] [MainThread]: Command `dbt test` failed at 13:42:56.664487 after 0.17 seconds
[0m13:42:56.665499 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A96BCD2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A984959C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022A98495990>]}
[0m13:42:56.666488 [debug] [MainThread]: Flushing usage events
[0m13:42:57.172628 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:44:02.588395 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A208CD330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A21FBD930>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A21FBD750>]}


============================== 13:44:02.592654 | 037a7f4a-2395-4fce-a683-972ac077515c ==============================
[0m13:44:02.592654 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:44:02.593655 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Felipe\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:44:02.594654 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Felipe\Documents\GitHub\Azure-Data-Eng-Pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:44:02.597656 [debug] [MainThread]: Command `dbt test` failed at 13:44:02.597656 after 0.09 seconds
[0m13:44:02.598666 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A208CD330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A21FBDA20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A21FBD9F0>]}
[0m13:44:02.598666 [debug] [MainThread]: Flushing usage events
[0m13:44:03.036723 [debug] [MainThread]: An error was encountered while trying to flush usage events
